# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-13 13:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postIssue', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='draft',
            new_name='isChecked',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='publish',
        ),
    ]
